name: CI - Build CLI

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build CLI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: pyinstaller MountRoot.spec
      - run: cd dist; zip ../MountRoot.zip MountRoot
      - name: Upload Binary to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MountRoot
          path: MountRoot.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MountRoot.zip
          tag: ${{ github.ref }}
          file_glob: true